### ISSUE TITLE
options issue

### ISSUE THREAD

**Issue by YKKate** [chmln/vue-wysiwyg#29] opened 2017-11-24 08:57 UTC
Hello, I found the config options is not working.
It seems like the option has been missed in the js, Because after I use the code from the left column of [this](https://github.com/chmln/vue-wysiwyg/issues/15#issuecomment-332139255), the options is working.(But the table is not defined)

Thank for the plugin, it's the only one wysiwyg plugin I can use.

**Comment by nawalnew** [comment] 2017-11-24 09:17
#25 

Try the newest VueJS and vue-wysiwyg. Could be the fix. Worked for me.

**Comment by YKKate** [comment] 2017-11-24 09:31
I update VueJS, Vue-cli, and vue-wysiwyg. 
It looks the same.

And when I clicked the toolbar btn, the dashboard is flash.

**Comment by nawalnew** [comment] 2017-11-24 13:58
My Config is: 
import wysiwyg from "vue-wysiwyg";
import "vue-wysiwyg/dist/vueWysiwyg.css";
Vue.use(wysiwyg, {
  hideModules: {
    headings: true
  }
}); 


It works at my project. maybe you did not include it right oder a typo?

**Comment by YKKate** [comment] 2017-11-27 03:26
My confusion is that when I replace the code 'node_modules/vue-wysiwyg/dist/vueWysiwyg.js' with the code in #15 ,it is successful.

**Comment by chmln** [comment] 2017-12-15 18:15
This is a duplicate of #30, and #30 is now fixed :tada:

**Closed by chmln** 2017-12-15 18:15 UTC
